apiVersion: v1
kind: Service
metadata:
  name: tetris-deployment   # Specify the deployment name directly
spec:
  selector:
    app: tetris
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
